In [1]:
import geopandas as gpd

In [2]:
# Load the shapefile
shapefile_path = r"D:\UNI_Stir\Projects\CI2D3\InProgress\reproj\ci2d3\CCIN12678_20181113_CI2D3_01.shp"  # Replace with your shapefile path
gdf = gpd.read_file(shapefile_path)

In [3]:
gdf.columns

Index(['inst', 'lineage', 'calvingyr', 'calvingloc', 'area', 'perimeter',
       'length', 'lon', 'lat', 'scenedate', 'imgref', 'mothercert', 'shpcert',
       'georef', 'ddinfo', 'sensor', 'beam_mode', 'pol', 'geometry'],
      dtype='object')

In [7]:
gdf[gdf['inst'].apply(lambda x: x.split('_')[-1]).duplicated()]

,inst,lineage,calvingyr,calvingloc,area,perimeter,length,lon,lat,scenedate,imgref,mothercert,shpcert,georef,ddinfo,sensor,beam_mode,pol,geometry
58,20080810_155412_es_1_JVU,20080810_004229_es_2_XRJ,2008,PG,1.3637,4.8684,1592.880,-65.543151,80.963652,2008-08-10 15:54:12,20080810_155412_es_wsm___hh_a_lcc.tif,1,2,100-200m,drifting,es,wsm,hh,"POLYGON ((593258.081 4690423.748, 593274.004 4..."
147,20080917_222514_r2_0_RYY,20080915_223046_r1_0_TNJ,2008,PG,21.1875,20.0026,7486.370,-77.161621,76.286476,2008-09-17 22:25:14,20080917_222514_r2_scwa__hh_a_lcc_.ti,1,1,200-400m,drifting,r2,scwa,hh,"POLYGON ((587650.026 4103512.033, 587486.782 4..."
228,20090306_014352_es_0_CAT,20090304_144419_es_0_LVO,2008,PG,13.8802,15.7048,5777.020,-63.108555,64.826191,2009-03-06 01:43:52,20090306_014352_es_wsm___hh_a_lcc.tif,1,1,0-100m,drifting,es,wsm,hh,"POLYGON ((1607517.420 3226299.278, 1607493.243..."
273,20090626_102625_r2_6_LTX,20090625_105548_r2_0_BKG,2008,PG,0.1529,1.7053,704.904,-64.198244,62.280613,2009-06-26 10:26:25,20090626_102625_r2_scwa__hx_a_lcc.tif,1,1,200-400m,drifting,r2,scwa,hx,"POLYGON ((1709168.772 2965732.810, 1709137.054..."
351,20100807_205030_r2_0_DNQ,20100806_153658_es_4_PBV,2010,PG,3.7413,8.8981,2909.640,-61.968747,81.067742,2010-08-07 20:50:30,20100807_205030_r2_scwa__hx_a_lcc.tif,2,1,>400m,drifting,r2,scwa,hx,"POLYGON ((641274.933 4735303.519, 641095.016 4..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25356,20131225_214118_r2_0_INI,20131225_200038_r2_0_QSI,NA,RG,1.8252,5.7343,2233.030,-67.849764,80.472422,2013-12-25 21:41:18,20131225_214118_r2_scwa__hx_a_lcc.tif,1,2,>400m,drifting,r2,scwa,hx,"POLYGON ((584069.527 4619035.299, 584046.256 4..."
25357,20131227_122255_r2_0_OQU,20131225_214118_r2_0_INI,NA,RG,1.8252,5.7343,2233.030,-68.516090,80.163184,2013-12-27 12:22:55,20131227_122255_r2_scwa__hx_a_lcc.tif,1,2,>400m,drifting,r2,scwa,hx,"POLYGON ((590384.174 4583613.094, 590394.997 4..."
25358,20131229_112720_r2_6_JHG,20131228_215016_r2_8_QPT,NA,RG,2.5000,7.1279,2621.740,-66.975154,68.470370,2013-12-29 11:27:20,20131229_112720_r2_scwa__hx_a_lcc.tif,1,2,200-400m,grounded?,r2,scwa,hx,"POLYGON ((1257643.092 3474703.662, 1257520.542..."
25359,20131230_105824_r2_1_LZV,20131229_112720_r2_4_BTE,NA,RG,4.9236,8.7757,3093.020,-67.536853,68.631616,2013-12-30 10:58:24,20131230_105824_r2_scwa__hx_a_lcc.tif,1,2,0-100m,trapped,r2,scwa,hx,"POLYGON ((1228172.494 3478754.513, 1228177.793..."
25363,20131230_105824_r2_3_RHK,20131229_112720_r2_6_JHG,NA,RG,2.5000,7.1279,2621.740,-66.961397,68.468395,2013-12-30 10:58:24,20131230_105824_r2_scwa__hx_a_lcc.tif,1,2,0-100m,grounded?,r2,scwa,hx,"POLYGON ((1258225.177 3474789.652, 1258102.626..."

In [15]:
gdf['inst_suffix'] = gdf['inst'].apply(lambda x: x.split('_')[-1])

gdf[gdf['inst_suffix'].duplicated()].sort_values('inst_suffix')

,inst,lineage,calvingyr,calvingloc,area,perimeter,length,lon,lat,scenedate,imgref,mothercert,shpcert,georef,ddinfo,sensor,beam_mode,pol,geometry,inst_suffix
1975,20101225_111048_r2_16_AAD,20101211_111849_r2_24_ENZ,2010,PG,0.0248,0.8314,270.951,-67.125068,70.827831,2010-12-25 11:10:48,20101225_111048_r2_scwa__hx_a_lcc.tif,1,2,0-100m,drifting,r2,scwa,hx,"POLYGON ((1125418.423 3695190.169, 1125436.630...",AAD
14267,20130704_125742_r2_7_AAE,20130702_221305_r2_1_PDL,2012,PG,0.7359,4.2304,1613.440,-85.236042,76.159953,2013-07-04 12:57:42,20130704_125742_r2_scwa__hx_a_lcc.tif,1,2,>400m,trapped,r2,scwa,hx,"POLYGON ((388453.548 4029191.306, 388454.458 4...",AAE
6386,20120211_102504_r2_1_AAE,20120210_105416_r2_1_VVJ,2010,PG,1.1784,4.8788,1631.090,-62.999687,67.576826,2012-02-11 10:25:04,20120211_102504_r2_scwa__hx_a_lcc.tif,1,2,200-400m,grounded?,r2,scwa,hx,"POLYGON ((1444855.370 3477330.900, 1444838.891...",AAE
16097,20130918_124052_r2_2_AAF,20130917_113040_r2_2_NTC,2012,PG,46.7708,33.3548,12275.700,-75.990362,76.759351,2013-09-18 12:40:52,20130918_124052_r2_scwa__hx_a_lcc.tif,1,1,>400m,grounded?,r2,scwa,hx,"POLYGON ((593997.161 4165986.346, 594033.053 4...",AAF
5399,20111029_220929_r1_5_AAI,20111028_215147_r2_4_QVM,2010,PG,1.0309,4.6811,1584.030,-78.676361,75.439365,2011-10-29 22:09:29,20111029_220929_r1_swa___hh_a_lcc.tif,1,2,200-400m,drifting,r1,swa,hh,"POLYGON ((583162.898 4002839.176, 582987.923 4...",AAI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11735,20121015_115929_r2_8_ZZX,20121014_222621_r2_8_AJA,2012,PG,13.1246,15.0534,5561.450,-79.186009,75.383957,2012-10-15 11:59:29,20121015_115929_r2_scwa__hx_a_lcc.tif,1,1,200-400m,drifting,r2,scwa,hx,"POLYGON ((571171.750 3994222.203, 571389.550 3...",ZZX
4465,20110727_220449_r2_7_ZZX,20110723_122400_r2_2_CKH,2010,PG,0.2409,2.2461,802.088,-78.463018,76.245622,2011-07-27 22:04:49,20110727_220449_r2_scwa__hh_a_lcc.tif,1,2,>400m,grounded?,r2,scwa,hh,"POLYGON ((558922.753 4088302.205, 558829.968 4...",ZZX
15993,20130911_124446_r2_8_ZZX,20130910_113345_r2_7_IXO,2012,PG,2.0917,8.0450,3271.050,-73.127665,78.663282,2013-09-11 12:44:46,20130911_124446_r2_scwa__hx_a_lcc.tif,1,2,>400m,drifting,r2,scwa,hx,"POLYGON ((578660.542 4389352.156, 578696.878 4...",ZZX
16173,20130916_215626_r2_11_ZZY,20130916_115946_r2_11_FPB,2012,PG,0.5483,4.3566,1612.670,-77.162868,76.131207,2013-09-16 21:56:26,20130916_215626_r2_scwa__hx_a_lcc.tif,1,1,>400m,drifting,r2,scwa,hx,"POLYGON ((596071.659 4088433.717, 596073.361 4...",ZZY
12850,20130317_123556_r2_7_ZZY,20130316_130501_r2_6_ZCD,2012,PG,2.3706,6.6949,2833.480,-71.445285,79.399185,2013-03-17 12:35:56,20130317_123556_r2_scwa__hx_a_lcc.tif,1,1,>400m,grounded,r2,scwa,hx,"POLYGON ((575694.208 4479870.165, 575775.794 4...",ZZY

In [12]:
gdf

,inst,lineage,calvingyr,calvingloc,area,perimeter,length,lon,lat,scenedate,imgref,mothercert,shpcert,georef,ddinfo,sensor,beam_mode,pol,geometry
0,20080713_235233_es_0_JWC,20080710_234704_es_0_P08,2008,PG,30.0189,32.1042,11202.000,-61.961521,81.088633,2008-07-13 23:52:33,20080713_235233_es_wsm___hh_a_lcc.tif,1,1,0-100m,drifting,es,wsm,hh,"POLYGON ((642583.831 4737010.036, 642584.251 4..."
1,20080718_161758_es_0_PUX,20080717_232648_es_0_AXI,2008,PG,5.0768,11.7517,4073.650,-61.748242,81.208505,2008-07-18 16:17:58,20080718_161758_es_wsm___hh_a_lcc.tif,1,1,0-100m,drifting,es,wsm,hh,"POLYGON ((635685.431 4748873.084, 635609.481 4..."
2,20080716_153449_es_3_POU,20080715_160601_es_2_KOE,2008,PG,0.2334,1.8947,663.533,-61.936536,81.094799,2008-07-16 15:34:49,20080716_153449_es_wsm___hh_a_lcc.tif,2,2,0-100m,drifting,es,wsm,hh,"POLYGON ((639153.035 4737837.194, 639121.726 4..."
3,20080714_163628_es_0_XKK,20080713_235233_es_0_JWC,2008,PG,30.0189,32.1042,11202.000,-62.001971,81.099975,2008-07-14 16:36:28,20080714_163628_es_wsm___hh_a_lcc.tif,1,1,0-100m,drifting,es,wsm,hh,"POLYGON ((641252.930 4737727.132, 641254.149 4..."
4,20080716_235405_es_0_UJN,20080716_153449_es_0_SMD,2008,PG,5.3063,11.9201,4132.140,-61.716621,81.204665,2008-07-16 23:54:05,20080716_235405_es_wsm___hh_a_lcc.tif,1,1,0-100m,drifting,es,wsm,hh,"POLYGON ((637178.217 4750031.227, 637124.459 4..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25359,20131230_105824_r2_1_LZV,20131229_112720_r2_4_BTE,NA,RG,4.9236,8.7757,3093.020,-67.536853,68.631616,2013-12-30 10:58:24,20131230_105824_r2_scwa__hx_a_lcc.tif,1,2,0-100m,trapped,r2,scwa,hx,"POLYGON ((1228172.494 3478754.513, 1228177.793..."
25360,20131230_105824_r2_0_VNJ,20131229_112720_r2_3_PTW,NA,RG,7.3202,11.4445,4575.050,-69.032463,71.439792,2013-12-30 10:58:24,20131230_105824_r2_scwa__hx_a_lcc.tif,1,2,0-100m,drifting,r2,scwa,hx,"POLYGON ((1036262.965 3721983.236, 1036301.407..."
25361,20131231_202545_r2_1_KQF,20131229_212329_r2_10_DRL,NA,RG,1.8252,5.7343,2233.030,-71.507132,79.430857,2013-12-31 20:25:45,20131231_202545_r2_scwa__hx_a_lcc.tif,1,2,>400m,drifting,r2,scwa,hx,"POLYGON ((574285.650 4482190.007, 574301.723 4..."
25362,20131231_220506_r2_1_YGC,20131231_202545_r2_1_KQF,NA,RG,1.5283,5.4587,2176.170,-71.590018,79.412478,2013-12-31 22:05:06,20131231_220506_r2_scwa__hx_a_lcc.tif,1,2,200-400m,drifting,r2,scwa,hx,"POLYGON ((573416.931 4479585.572, 573453.165 4..."
25363,20131230_105824_r2_3_RHK,20131229_112720_r2_6_JHG,NA,RG,2.5000,7.1279,2621.740,-66.961397,68.468395,2013-12-30 10:58:24,20131230_105824_r2_scwa__hx_a_lcc.tif,1,2,0-100m,grounded?,r2,scwa,hx,"POLYGON ((1258225.177 3474789.652, 1258102.626..."